### ISSUE TITLE
Change LICENSE to Apache2

### ISSUE THREAD

**Issue by elgalu** [smccarthy/chef-selenium-grid-extras#1]
Thank you so much for this project, however, could you change the license to [Apache 2.0 license](http://www.apache.org/licenses/LICENSE-2.0) ? currently one makes it unusable in my current employer.

**Comment by smccarthy** [comment]
Hi @elgalu . I will look at License's sometime today after work. I am leaning towards the Apache 2.0 license, but I don't know much about the different ones, so I just want to read up on them before choosing. Thanks!

**Comment by smccarthy** [comment]
@elgalu Does it have to be apache 2.0 to work for you? or does MIT license work as well?

**Comment by smccarthy** [comment]
I chose MIT because it was easier for me to understand and had less restrictions from what I can tell. If it does cause issues for anyone on using this license, let me know and I can consider changing it. Thank you!

**Comment by elgalu** [comment]
The problem with MIT is patent. Apache 2 is more permissive.

**Comment by smccarthy** [comment]
I updated the patent to Apache 2.0.

**Comment by elgalu** [comment]
Thanks! !!
